AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - lib/generators/clavis/templates/**/*
    - vendor/**/*
    - bin/**/*
    - db/**/*
    - node_modules/**/*

# For gems it's typical to declare development dependencies in the gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/MethodLength:
  Max: 45
  Exclude:
    - 'spec/**/*'
    - 'lib/clavis/controllers/concerns/authentication.rb'
    - 'lib/clavis/providers/base.rb'

Metrics/AbcSize:
  Max: 45
  Exclude:
    - 'spec/**/*'
    - 'lib/clavis/providers/base.rb'
    - 'lib/clavis/controllers/concerns/authentication.rb'

Metrics/CyclomaticComplexity:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/PerceivedComplexity:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 400

Metrics/ModuleLength:
  Max: 250

Metrics/BlockLength:
  Max: 60
  Exclude:
    - spec/**/*
    - clavis.gemspec

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Lint/EmptyClass:
  Exclude:
    - spec/**/*

# Ignore certain spec files with duplicate methods
Lint/DuplicateMethods:
  Exclude:
    - 'spec/integration/oauth_callback_spec.rb'

# Ignore missing super in test files
Lint/MissingSuper:
  Exclude:
    - 'spec/dummy/app/models/application_record.rb'
    - 'spec/dummy/app/models/user.rb'
