AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'lib/generators/clavis/templates/**/*'
    - 'lib/generators/clavis/**/templates/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
