AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - lib/generators/clavis/templates/**/*
    - vendor/**/*
    - bin/**/*
    - db/**/*
    - node_modules/**/*

Metrics/MethodLength:
  Max: 35
  Exclude:
    - spec/**/*
    - lib/clavis/controllers/concerns/authentication.rb

Metrics/AbcSize:
  Max: 35
  Exclude:
    - spec/**/*
    - lib/clavis/controllers/concerns/authentication.rb

Metrics/CyclomaticComplexity:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/PerceivedComplexity:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/BlockLength:
  Max: 60
  Exclude:
    - spec/**/*
    - clavis.gemspec

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Lint/EmptyClass:
  Exclude:
    - spec/**/*
