name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
          cache-version: 1
      - name: Run RuboCop
        run: bundle exec rubocop

  security:
    runs-on: ubuntu-latest
    name: Security
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
          cache-version: 1
      - name: Run Brakeman
        run: bundle exec rake brakeman

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
          cache-version: 1
      - name: Install dependencies
        run: |
          bundle config set --local with 'development test'
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rspec 