name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop

  security:
    runs-on: ubuntu-latest
    name: Security
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
      - name: Install Brakeman
        run: gem install brakeman
      - name: Run Brakeman
        run: bundle exec brakeman -z --no-exit-on-warn --no-exit-on-error

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec 