name: CI Local

# This workflow is only for local testing with act
# It will not run automatically on GitHub
on:
  workflow_dispatch: # Manual trigger only, won't run automatically

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Install required packages
        run: |
          apt-get update
          apt-get install -y git build-essential pkg-config libsqlite3-dev
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Run tests
        run: bundle exec rspec || echo "Tests failed, but we'll continue anyway for local testing"
        
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Install required packages
        run: |
          apt-get update
          apt-get install -y git build-essential
          
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path vendor/bundle
          bundle install --jobs 4 --retry 3
          
      - name: Run RuboCop
        run: bundle exec rubocop || echo "RuboCop found issues, but we'll continue anyway"
        
      - name: Run Brakeman
        run: |
          # Only run if app directory exists (for Rails projects)
          if [ -d "app" ]; then
            bundle exec brakeman -z --no-exit-on-warn --no-exit-on-error || echo "Brakeman found issues, but we'll continue anyway"
          else
            echo "No app directory found, skipping Brakeman"
          fi 