name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build & Test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: false
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libsqlite3-dev
          
      - name: Setup bundle cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-3.4.1-gems-${{ hashFiles('**/clavis.gemspec') }}-${{ hashFiles('**/Gemfile.lock') }}-v1
          restore-keys: |
            ${{ runner.os }}-ruby-3.4.1-gems-
            
      - name: Install dependencies
        run: |
          bundle config set --local path vendor/bundle
          bundle config set --local with 'test'
          bundle install --jobs 4 --retry 3
          
      - name: Run tests
        run: bundle exec rspec
        
      - name: Run RuboCop
        run: bundle exec rubocop
      
      - name: Run Brakeman
        run: |
          # Only run if app directory exists (for Rails projects)
          if [ -d "app" ]; then
            bundle exec brakeman -z --no-exit-on-warn --no-exit-on-error
          else
            echo "No app directory found, skipping Brakeman"
          fi
