name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build & Test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: false
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libsqlite3-dev
          
      - name: Setup bundle cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-3.4.1-gems-${{ hashFiles('**/clavis.gemspec') }}-${{ hashFiles('**/Gemfile.lock') }}-v1
          restore-keys: |
            ${{ runner.os }}-ruby-3.4.1-gems-
            
      - name: Install dependencies
        run: |
          bundle config set --local path vendor/bundle
          bundle config set --local with 'test'
          bundle install --jobs 4 --retry 3
          gem install rails # Ensure Rails is available for creating the test app
          gem install bcrypt # Ensure bcrypt is available for authentication
          
          # Verify bcrypt installation
          echo "Verifying bcrypt installation..."
          ruby -e 'require "bcrypt"; puts "bcrypt v#{BCrypt::VERSION} is successfully installed"'
          
      - name: Run tests
        run: bundle exec rake all_tests
        
      - name: Run RuboCop
        run: bundle exec rubocop
      
      - name: Run Brakeman
        run: |
          # Only run if app directory exists (for Rails projects)
          if [ -d "app" ]; then
            bundle exec brakeman -z --no-exit-on-warn --no-exit-on-error
          else
            echo "No app directory found, skipping Brakeman"
          fi
      
      - name: Build gem
        run: bundle exec rake build
        
      - name: Verify gem builds correctly
        run: |
          VERSION=$(ruby -r ./lib/clavis/version.rb -e "puts Clavis::VERSION")
          GEM_FILE="pkg/clavis-$VERSION.gem"
          if [ ! -f "$GEM_FILE" ]; then
            echo "Gem file not found: $GEM_FILE"
            exit 1
          fi
          echo "Gem built successfully: $GEM_FILE"
      
      - name: Upload gem artifact
        uses: actions/upload-artifact@v4
        with:
          name: gem-package
          path: pkg/*.gem
          retention-days: 7
