name: Rails 8 Test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby 3.3.0 with Rails 8.0
    
    steps:
      - name: Install required packages
        run: |
          apt-get update
          apt-get install -y git build-essential pkg-config libsqlite3-dev
    
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path vendor/bundle
          bundle add activesupport --version "~> 8.0.0"
          bundle install --jobs 4 --retry 3
          
      - name: Run tests
        run: bundle exec rspec 