name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (must match version.rb)'
        required: true
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Verify version matches
        run: |
          VERSION_IN_CODE=$(ruby -r ./lib/clavis/version.rb -e "puts Clavis::VERSION")
          if [ "$VERSION_IN_CODE" != "${{ github.event.inputs.version }}" ]; then
            echo "Version mismatch: $VERSION_IN_CODE (in code) vs ${{ github.event.inputs.version }} (specified)"
            exit 1
          fi
          echo "Version matches: $VERSION_IN_CODE"

      - name: Run tests
        run: bundle exec rake spec

      - name: Build gem
        run: bundle exec rake build
        
      - name: Verify gem builds correctly
        run: |
          GEM_FILE="pkg/clavis-${{ github.event.inputs.version }}.gem"
          if [ ! -f "$GEM_FILE" ]; then
            echo "Gem file not found: $GEM_FILE"
            exit 1
          fi
          echo "Gem built successfully: $GEM_FILE"

  release:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for proper tagging

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up RubyGems credentials
        run: |
          mkdir -p ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials

      - name: Release gem
        run: |
          GEM_VERSION="${{ github.event.inputs.version }}"
          
          # Create an annotated tag
          git tag -a "v$GEM_VERSION" -m "Release v$GEM_VERSION"
          git push origin "v$GEM_VERSION"
          
          # Release the gem
          gem build *.gemspec
          gem push "clavis-$GEM_VERSION.gem"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            *.gem
            pkg/*.gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 